compile:
  libraries:
    - ArduinoLog
    - TaskManagerIO
  platforms:
    - uno
    - due
    - mega2560
    - leonardo

unittest:
  libraries:
    - ArduinoLog
    - TaskManagerIO
  platforms:
    - uno
    - due
    - mega2560
    - leonardo
