compile:
  libraries:
    - ArduinoLog
    - TaskManagerIO
  platforms:
    - esp32

unittest:
  libraries:
    - ArduinoLog
  platforms:
    - uno
    - due
    - mega2560
    - leonardo
    - esp32
